(Q)1)Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations?

#Ans:-The purpose and Advantages of Numpy in scientific computing and data analysis are

(.)Numpy are used so that it easily handle complex task , handle arrays, mathematical operation etc.It also provide various collections of mathematical tools
like:-Linear algebra,Sin,cos etc.

(.)Numpy are homogeneous in nature.

(.)It enhance python capabilities for numerical operations because numpy array was created by using "c" which is one of fastest language and  it is used to operate mathematical operations easily,as it is homogeneous in nature.

(Q)2)Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

#Ans:-np.mean and np.average is mostly similar in nature.
(.)np.mean work is to give average value of numbers which is given in input,np.mean is mostly used in "Numpy".Module Numpy has no attribute "np.average".

(.)np.average work's is to give average value of numbers.
Numpy has no attribute "average", that's why it is not used in numpy.it is used in some other modules
like:-list,etc..


(Q)3)Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays.

#(Ans):-The methods for reversing a Numpy array along different axes are
(.)If you want to reverse the Numpy array ,then you use ".T" for reversing from both axes.If you did ".T",Row become column and column become Rows.


In [4]:
#Ex:-
import numpy as np
ar=np.array([1,2,3,4]) #It is one dimension(1d) array
ar

array([1, 2, 3, 4])

In [17]:
ar.T

array([1, 2, 3, 4])

In [18]:
ar.ndim

1

In [35]:
#2d array#
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
arr.ndim

2

(Q)4)How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance

#Ans:-We can check the data type of numpy array by using "dtype".It returns the data type of all the elements which is present in array.


In [37]:
#Exampel:-
at=np.array([1,2,3,4])
at

array([1, 2, 3, 4])

In [39]:
at.dtype

dtype('int64')

importance of data types in memory management and performenc are 
(.)All the elementswhich is present in array  will pointing to yhe same memory location because it is in homogenous in nature.

(Q)5)Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#Ans:-Ndarray is known as N dimensional arrays.Ndarrays size is fixed ,it cannot be changed.

Their key features are
(.)Firstly,Once size is define then it cannot be change.
like:-
a=np.array((3,4))
Answer come in the size of (3,4) ,it cannot be (3,3),(3,5),etc..

They differ from standard python lists because Numpy array are much faster and have strict requirement on homogeneity.
on the other hand , python lists have lesser faster as compared to Nd array and it have not strict requirement on homogeneity.

(Q)6)Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#Ans:-The performance benefits of Numpy arrays over python lists for numerical operations is that Numpy arrays is much faster as compared to Python lists because it is homogeneous in nature that's why it mathematical operation is much faster than Python lists.

(Q)7)Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output.

#Ans:-The main difference between vstack() and hstack() is that vstack() combine Numpy arrays vertically and hstack combine Numpy arrays horizontally.

In [10]:
#Example:-
import numpy as np
ar=np.array([[1,2,3],[4,5,6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.vstack(ar)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.hstack(ar)

array([1, 2, 3, 4, 5, 6])

(Q)8) Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions.

#Ans:-The differences between fliplr() and flipud() methonds in Numpy is that ,flipud() can flip arrays in the vertical direction.
fliplr() can flip in any direction.

In [13]:
np.flipud(ar)

array([[4, 5, 6],
       [1, 2, 3]])

In [17]:
np.fliplr(ar)

array([[3, 2, 1],
       [6, 5, 4]])

(Q)9)Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#Ans:-Array_spli() is used to split into multiple sub array.
It handle uneven splits and any remaining elements.

(Q)10)Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

#Ans:-vectorization is the process of converting algorithm from single operating value.
Brodcasting 